In [1]:
import numpy as np
import random
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
iris = datasets.load_iris() #load iris dataset
X= iris.data 
y= iris.target 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
#shuffle and split the iris dataset. %70 of the rows in the data as the training set, %30 of the rows in the data test set.

In [2]:
print(iris.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [3]:
print(iris.feature_names) #name of features in iris dataset
print(iris.target_names) #name of targets in iris dataset

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [4]:
print(iris.data.shape) #dimension and size of iris dataset
print(X_train.data.shape)
print(X_test.data.shape)
print(y_train.data.shape)
print(y_test.data.shape)

(150, 4)
(105, 4)
(45, 4)
(105,)
(45,)


In [5]:
print(iris.data) #features

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [6]:
print(iris.target) #setosa=0, versicolor=1, virginica=2

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [7]:
def euclidean (row1, row2): #it takes two arrays as parameters.One of them is test row and the other is train row.
    distance =0.0 #we initially set the distance to 0
    for i in range(len(row1)): 
        distance+=pow((row1[i]-row2[i]),2) #Due to Euclidean's rule, we subtracted the arrays according to their index and square them
    return np.sqrt(distance) 

In [8]:
def find_distances(X_train,X_test,y_train,k):
    distances = []
    for i in range(len(X_train)): #X_train has 105 rows so this loop is performed until the train rows are finished.
        distance = euclidean(X_train[i],X_test) #The distance of the test row and the i'th train row is calculated according to the Euclidean rule for 4 features and we get a distance. 
        distances.append((y_train[i], distance)) #The distance which we found is added to the array of distances
    distances.sort(key=lambda distances: distances[1]) #When the distance calculation is complete, the resulting array is ordered according to their distance from small to large.
    return distances[:k] #The nearest k neighbor array is returned

In [9]:
def count(vote_labels):
    count = list()
    np_vote_labels = np.array(vote_labels)
    np_unique_vote_labels = np.unique(np_vote_labels) ##find unique labels
    for i in range(len(np_unique_vote_labels)): ##count unique labels in the array and add that number to another array.
        count.append([np_unique_vote_labels[i],vote_labels.count(np_unique_vote_labels[i])])
        max=0
    for i in range(len(count)): #max function to find which label is more
        if max < count[i][1]:
            label=count[i][0] #most common label
            max=count[i][1]
    return label 

In [10]:
def predict(X_train,X_test,y_train,k):
    output=[]
    for i in range(len(X_test)): ##X_test has 45 rows
        neighbors =[]
        neighbors = find_distances(X_train,X_test[i],y_train,k) #The nearest k neighbor arrays which we calculated are assigned to the neighbors array
        vote_labels=[]
        for j in range(k): #append labels which belong to k neighbors
                vote_labels.append(neighbors[j][0])   
        output.append(count(vote_labels)) #count function returns the most label in the array and we add this label to output array.
    return output

In [11]:
for k in [1,3,5]: #it gives outputs and scores for k=1,3,5
    output = predict(X_train,X_test,y_train,k)
    print("For k=",k, "\nOutput=",output)
    print("Accuracy Score for k=",k,":",accuracy_score(y_test, output),"\n")

For k= 1 
Output= [2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0, 0]
Accuracy Score for k= 1 : 0.9777777777777777 

For k= 3 
Output= [2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0, 0]
Accuracy Score for k= 3 : 0.9777777777777777 

For k= 5 
Output= [2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0, 0]
Accuracy Score for k= 5 : 0.9777777777777777 



In [12]:
#Checking whether it works for a random value of k
random_k =random.randint(1,15) #a value is chosen
random_output = predict(X_train,X_test,y_train,random_k) #and tested
print("For k=",random_k, "\nOutput=",random_output)
print("Accuracy Score for k=",random_k,":",accuracy_score(y_test, random_output),"\n") #score calculation for a random k

For k= 8 
Output= [2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1, 0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0, 0]
Accuracy Score for k= 8 : 0.9777777777777777 



In [ ]:
#Checking whether it works for an arbitrary value of k
arbitrary_k=input("k:")
arbitrary_output = predict(X_train,X_test,y_train,int(arbitrary_k)) #tested
print("For k=",arbitrary_k, "\nOutput=",arbitrary_output)
print("Accuracy Score for k=",arbitrary_k,":",accuracy_score(y_test, arbitrary_output),"\n") #score calculation for an arbitrary k